name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "www.zsu.gov.ua"
    port: 8880
    uuid: "a9fb0f8c-89e9-44ee-9574-a310c5bd259c"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "autumn-leaf-eefd.119-38e.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "192.145.31.5"
    port: 8443
    uuid: "9f73cf9a-c68f-4e6d-90f0-e66b64f52f8a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "neth9.lunariai.ru"
    client-fingerprint: "chrome"
    alpn: ["h2", "http/1.1"]
  - name: "@rossinna77Github"
    type: vless
    server: "fancy-king-6fb5.33-615.workers.dev"
    port: 8880
    uuid: "243ad93d-9732-4e19-9784-8b1a642cff70"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@rossinna77Github"
    type: vless
    server: "cf6.466688.xyz"
    port: 8880
    uuid: "f989cbf4-40d2-41d2-8a00-1fe4e29b2192"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "ancient-rice-c180.455-8ad.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.70.21"
    port: 8080
    uuid: "b2c879ed-08a2-4a79-9c57-37c7db614e96"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "sweet-cake-1340.474-288.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "31.58.50.200"
    port: 8443
    uuid: "757e753e-85e2-482e-a29b-852ad193bc5f"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mr5AF0LFyDzYDRoYAwH6QNcHXL77-LoiwRx50ZzU8QU"
  - name: "@rossinna77Github"
    type: vless
    server: "log.bpminecraft.com"
    port: 8880
    uuid: "7ed93ccf-6a54-4b19-a9b4-aedfc79bab7d"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "muddy-sky-4767.344-7a7.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "172.67.161.104"
    port: 8880
    uuid: "1a5e2e63-64e2-4737-95b6-c2ee60c979a1"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "wild-mode-4ca6.234-8f6.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.70.21"
    port: 8080
    uuid: "9c772ed7-2843-4554-9a96-4a88f827de58"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "nameless-tree-08b8.352.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "31.58.181.88"
    port: 8443
    uuid: "70bd60b1-f399-4df4-ad32-9adc40ae5f2c"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AERbWB2uslqIzm1hSlOZZEH3Y9qg_zlWRRyLfh97kXc"
  - name: "@rossinna77Github"
    type: vless
    server: "146.70.124.85"
    port: 443
    uuid: "40abbe13-f02e-4da2-9b19-966c2c3eb4ee"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.datadoghq.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "byzvlw97wjAAAfHs5AZRV0P0H6_JKBEZ4yfLS0HNewE"
      short-id: "fe24f8a0a560056e"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.23.72"
    port: 8880
    uuid: "a62a4c64-2270-4d41-828b-2591906c48ba"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "sweet-disk-a026.253-54b.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "188.114.97.6"
    port: 8080
    uuid: "6b89f475-913c-4381-a102-f5e06a129685"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "proud-dawn-56f1.125-85b.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "172.67.174.37"
    port: 8880
    uuid: "fba6d1fd-0dab-428d-ae71-0e64c73a6060"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "morning-wood-0e8a.28-63e.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.151.134"
    port: 8880
    uuid: "9bf81377-d077-4569-9fc9-5f0a55180651"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "super-feather-91c4.267.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "188.114.97.6"
    port: 8080
    uuid: "81d55675-8570-4b40-9a77-3125339a0f86"
    udp: true
    network: ws
    ws-opts:
      path: "/ "
      headers:
        Host: "spring-sound-8d8e.36-9ff.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.70.21"
    port: 8080
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "damp-surf-aacf.296-8ed.workers.dev"
    port: 8880
    uuid: "b4883d27-3151-4adf-92b1-841c0dccd1ea"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.56.202"
    port: 8880
    uuid: "5990e0a5-fc5f-43c6-8fdc-39612c60a9cd"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip"
      headers:
        Host: "jolly-butterfly-24e0.212-cb3.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "172.67.169.35"
    port: 443
    uuid: "ef5c5d5c-08c6-4549-b05e-d1ff29ecc8ba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "7-M16.pAttAYa-8.kdnS.fR"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/JRr6VGcSLFc034DC6sDbwyWJLbB"
      headers:
        Host: "7-M16.pAttAYa-8.kdnS.fR"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.23.72"
    port: 8880
    uuid: "4e81922a-1c2e-41ee-bb4c-9095a0a363fe"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "gentle-cell-501a.273-d6b.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "OV-France1.09vpn.com"
    port: 80
    uuid: "f5c47e9c-914a-4a91-a81e-a5a77bc10fc1"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.32.103"
    port: 8880
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "172.67.210.96"
    port: 443
    uuid: "a90c264d-3853-4eef-9a3d-628b2d02d15e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "0-m19.SOUth-AFricA-LINE.ccwu.Cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/CjBjB9sn5pCvaSwScc"
      headers:
        Host: "0-m19.SOUtH-afRIca-lInE.ccWu.Cc"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
