name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "104.18.43.76"
    port: 8880
    uuid: "a429499b-6237-44b2-ae4d-0d53d14cf46a"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "small-wave-9851.441-57f.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.17.148.22"
    port: 443
    uuid: "cb33f1fc-5b49-4e16-882b-8aee00000000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "netlivpn0919.vsh72727.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn0919.vsh72727.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "45.195.111.15"
    port: 443
    uuid: "45459159-1536-4e98-95b3-aa1dbbfb4172"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "storage.yandex.net"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "7zd9mJilgjOrg_ohtw23Vmio-pdnYqeP_r-kiWt87Cg"
      short-id: "2715592069f36fe7"
  - name: "@rossinna77Github"
    type: vless
    server: "72.56.92.177"
    port: 40443
    uuid: "4480161e-2c59-4d37-8736-675c9af32bf1"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "deepl.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fWzCKXwvMXaacsl1DdFb1vKQ9l9cTK1G7udqmaYHL0Y"
      short-id: "01d1bf2d4755d40c"
  - name: "@rossinna77Github"
    type: vless
    server: "jdwabxe.cvewfjg.shop"
    port: 443
    uuid: "711c018e-2692-4aa8-93f3-544d83fcd16c"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HyVSZ2OyySwXT-xRhTAqoiuYflIaj_b0Jxm7S1Iq9hs"
      short-id: "7a76f3c4b9dd"
  - name: "@rossinna77Github"
    type: vless
    server: "152.53.114.186"
    port: 443
    uuid: "ab7d5ea9-6eca-47c3-b14b-67378fc2d7c2"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "as.tunnelx.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "UO3EObgU3xUrhIGEE0gfCn5ZOz8YxNcwwW6ZaYzD3SA"
      short-id: "4e9b0c2d1a3f5768"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
