name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "79.137.199.52"
    port: 21
    uuid: "763e2ddd-c830-4f4f-801c-f6f2c3418d4f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "154.83.2.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime28.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "45.76.87.125"
    port: 14750
    uuid: "c2c94230-7075-4558-89f4-ddf74d7de107"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "45.131.66.247"
    port: 20002
    uuid: "698e5db2-31ad-44ba-8158-59a03edbfd92"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.147.143"
    port: 8880
    uuid: "11046a7c-fa1b-4653-ab87-400feb465540"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "nameless-poetry-12fb.8-0a2.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "204.216.216.23"
    port: 10086
    uuid: "9f0285ee-20ca-4953-bcdb-86a920652923"
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "n8.loyalemu.sbs"
    port: 8443
    uuid: "6df75f42-4447-4ade-a53e-350f4eb69858"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "n8.loyalemu.sbs"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/ws8"
      headers:
        Host: "n8.loyalemu.sbs"
  - name: "@rossinna77Github"
    type: vless
    server: "peekconfigg.vipserver1-39d.workers.dev"
    port: 2096
    uuid: "7c6a566b-4c4a-b8f2-1719-a3096b424141"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "peekconfigg.vipserver1-39d.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "peekconfigg.vipserver1-39d.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "8.219.155.125"
    port: 443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "0h3qt.oqwt.pl0.hh.vavava.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "0h3qt.oqwt.pl0.hh.vavava.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "50.62.194.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime37.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.18.37.228"
    port: 443
    uuid: "83afd88f-200f-4d89-bfc7-66eff160c1d8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "josni.hoyes.cloudns.ch"
    network: ws
    ws-opts:
      path: "musiclovers85?ed=512"
      headers:
        Host: "josni.hoyes.cloudns.ch"
  - name: "@rossinna77Github"
    type: vless
    server: "104.18.35.73"
    port: 8443
    uuid: "24916ad0-847d-4522-9e17-f4347dee57fd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kv.074167.xyz"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "kv.074167.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "cf5.466688.xyz"
    port: 8880
    uuid: "9be3bb59-c281-4fee-ae3d-7cf6c4b47eb4"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "late-mountain-6801.355.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "upward-puma.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "upward-puma.rooster465.autos"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
  - name: "@rossinna77Github"
    type: vless
    server: "172.67.68.240"
    port: 8880
    uuid: "05e7abc2-46e1-4a23-9cdc-173ce17eb0d4"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip"
      headers:
        Host: "round-term-947c.41-332.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.16.72.50"
    port: 8880
    uuid: "15ce0fde-88e2-42b0-91e6-e4a1b4568f6e"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip"
      headers:
        Host: "old-truth-de8a.110-187.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.171.132.185"
    port: 4100
    uuid: "112912a9-cedf-485d-b8ed-d8f8d4774437"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.152.241"
    port: 2095
    uuid: "86c50e3a-5b87-49dd-bd20-03c7f2735e40"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fuckingfangbinxing.pusytroller.cf"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.89.181"
    port: 8880
    uuid: "2b5753cf-4d0a-4746-b63d-cd67a3de2ccc"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "crimson-hill-8061.166-dcf.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "31.58.50.200"
    port: 8443
    uuid: "e042b105-41f0-4fb7-8e7c-46a0cc6044e0"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mr5AF0LFyDzYDRoYAwH6QNcHXL77-LoiwRx50ZzU8QU"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.147.119"
    port: 8880
    uuid: "11046a7c-fa1b-4653-ab87-400feb465540"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "nameless-poetry-12fb.8-0a2.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "www.speedtest.net"
    port: 443
    uuid: "a7c801a1-3eb8-424e-bfcd-652000000000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "netlivpn0004.svsv2626.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn0004.svsv2626.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "soskeynets.0m68-qz3hqyfnlar6n3iq.workers.dev"
    port: 443
    password: "Telegram_healer_config"
    sni: "30F67SBQ8jJWMT7gytfc14.0m68-qZ3hqYFNlaR6n3Iq.WorKerS.Dev"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/tr/MBHDTiG2ZHfgBBj9iEpRFkse0tafJ?ed=2560"
      headers:
        Host: "30f67sbq8jjwmt7gytfc14.0m68-qz3hqyfnlar6n3iq.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "166.62.113.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/Telegram-WangCai2"
      headers:
        Host: "notls.lukongtou.eu.org"
  - name: "@rossinna77Github"
    type: vless
    server: "netraidly.ru"
    port: 40443
    uuid: "4480161e-2c59-4d37-8736-675c9af32bf1"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "deepl.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fWzCKXwvMXaacsl1DdFb1vKQ9l9cTK1G7udqmaYHL0Y"
      short-id: "01d1bf2d4755d40c"
  - name: "@rossinna77Github"
    type: vless
    server: "cf5.466688.xyz"
    port: 8880
    uuid: "1a5e2e63-64e2-4737-95b6-c2ee60c979a1"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "wild-mode-4ca6.234-8f6.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "cf7.466688.xyz"
    port: 8880
    uuid: "9be3bb59-c281-4fee-ae3d-7cf6c4b47eb4"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "late-mountain-6801.355.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "31.58.50.200"
    port: 8443
    uuid: "fe5cb9d9-0d9e-41fe-940f-c6c97f7d9157"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mr5AF0LFyDzYDRoYAwH6QNcHXL77-LoiwRx50ZzU8QU"
  - name: "@rossinna77Github"
    type: trojan
    server: "better-molly.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "better-molly.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "185.193.28.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    network: ws
    ws-opts:
      path: "telegram-wangcai2🇨🇳"
      headers:
        Host: "notls.lukongtou.eu.org"
  - name: "@rossinna77Github"
    type: vless
    server: "8.47.69.0"
    port: 8880
    uuid: "a8178248-3cdf-4fb0-ab7b-87c1ab77201c"
    udp: true
    network: ws
    ws-opts:
      path: "/cdn/assets/stream"
      headers:
        Host: "cnd.france2.gg.newwaycdn.com"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.88.168"
    port: 8880
    uuid: "2e55e846-7737-4c07-af67-191e2727513c"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "weathered-sunset-be54.407-d9d.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "gr1.levikogjgfdd.ir"
    port: 443
    uuid: "eda6b321-aa59-4b1e-b823-3616af020b4a"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "play.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8Cho6K3KB6Aoty9x_TCAbY3yv7m-ToCHqaKkZTxR3jM"
      short-id: "d6c3c9"
  - name: "@rossinna77Github"
    type: vless
    server: "192.204.33.111"
    port: 56679
    uuid: "4935bf38-dd83-454a-ba0f-6fa18c418fc0"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "nXNWy2NMbCitk1oBQwEmbattbPeIC1vYpNrCahGFlRc"
      short-id: "574fb961ca6be4"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
