name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "8c9be850-32a0-4cc1-809b-4a5161413a90"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "sparkling-frog-59e1.256-d4e.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "14c80e0e-f7ce-4991-94fc-99a1db4a9b1e"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "aws.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ZJRnFU-1s1JOnO8E9uZ7b00l1fPEh63fGRbdBANFRno"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "91c35e01-00bf-41f5-94e4-71539222d255"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "grimness-backlogs.cdn-content.com"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "grimness-backlogs.cdn-content.com"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "10000025-9781-8767-f000-d3b3363ba020"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "strapi.io"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "cWVHOLypYFtzpvgldlZ5h1fhOTptEC-ZQI7pFb7ok0c"
      short-id: "5e11872495085a8f"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "086422b2-3347-45f8-b527-d9e1be25dc56"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "yandex.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "pBd5IOD_sCDpIDqgi6EtZ6DAAMGns9n2C3qPH0i3Tno"
      short-id: "0e29dc68"
    network: grpc
    grpc-opts:
      grpc-service-name: "UpdateService"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "8fb65472-5957-4f64-ba2d-b5812b2f155a"
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "018a6ab7-f54c-4a1c-bfc5-d6b04e6545d1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ghosts-spasm.quick-cdn.net"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "ghosts-spasm.quick-cdn.net"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c40f773e-3b96-417e-b22c-e48cb63ca7d9"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "l5eAOSPQMEyzEPvWGAKvCkcPpsJvR3DJfYo6elw1UTE"
      short-id: "3b802dad547b0847"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "node21.mxvpn.dev"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "bf645ffe-a3cc-4480-8e4c-9bcd1af41052"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "rTnh7Y8RsSA5HSvFf-pWT49x8va6U6XHMRgNiMuwB0A"
      short-id: "ab88d256"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "220046c3-0081-4c22-a648-83a52bc3a0d5"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "yellow-sky-38b3.154-d73.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "db320947-adfb-400d-b60b-383b8324bffe"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "deepl.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "aZOpodpnifoxDqTzWgxJRffgsiGnG9-h-EZd4SvOImc"
      short-id: "f7b2"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a1de0630-5786-48a0-84f6-dc6f2de10d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vlso5.1d.mom"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/socks5=888:888@hkip.1d.mom:1080"
      headers:
        Host: "vlso5.1d.mom"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b5ca5ab3-8cbc-4ac3-89da-9cd360589ecb"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "savesafe.co"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "6z3YcVP0f2pK3iANKIkBUZOgNeErDjxY83mHZG5jrnI"
      short-id: "f63805c3ecc7a483"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "41ce10f9-748b-46a0-be7c-e29d863aa028"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d829cf8d-0a32-4e60-bcc3-a03fb4658ea4"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip"
      headers:
        Host: "shy-wind-a26f.182-104.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d6c595c9-bff4-4510-893a-dfa3c87fa0cd"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip"
      headers:
        Host: "lucky-cell-d20c.78-107.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "8fb65472-5957-4f64-ba2d-b5812b2f155a"
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "zb1zi.s3nx.dyz.hh.vavava.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "3e7bb66e-d7c6-4711-aa05-e4ab0ec58c6d"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "shrill-cell-cca7.158-6fa.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fx3h2kf8xn.fx6hsv0.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fx3h2kf8xn.fx6hsv0.ccwu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c27949e6-d897-415f-8aed-01a18bbff1a5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fm3.pages.dev"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "fm3.pages.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "9bf81377-d077-4569-9fc9-5f0a55180651"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "super-feather-91c4.267.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "a126f35c-e832-4115-8593-b723ade3f7be"
    sni: "hk.catxstar.com"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4a239f83-479c-4790-a9c7-fe7ddd483a4c"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AERbWB2uslqIzm1hSlOZZEH3Y9qg_zlWRRyLfh97kXc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "dc53f855-5025-45c8-9a85-981036839c5c"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "summer-breeze-0574.279.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
