name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "51a0af77-a60c-4d9b-81a4-f50e1b38d90b"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "refighehosein.salamdadash123.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a90c264d-3853-4eef-9a3d-628b2d02d15e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1-m19.LoP.CCWu.CC"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/CjBjB9sn5pCvaSwScc"
      headers:
        Host: "1-m19.Lop.ccwU.CC"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "72fbb611-628d-4afa-8198-bda3e38021f9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "3t1yvbyla-rj740g.28m7r63dttya6gazmhoo.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "3t1yvbyla-rj740g.28m7r63dttya6gazmhoo.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "fe34b5df-e634-4c83-a057-e53f41ce8e27"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lATE-LaB-d6A2.CIwodA8715.WoRKerS.DeV"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiQ3dmV1d4OUFQdSIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0"
      headers:
        Host: "late-lab-d6a2.ciwoda8715.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime04.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "66ac188b-bd8d-4218-b9ba-0bad0e152cd0"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "s2uiu3GQA2SlZzsr86Z5Dav97eAFTPf7Nvr-zqzzRgg"
      short-id: "72ccd4a7563c2953"
    network: grpc
    grpc-opts:
      grpc-service-name: "9d30d49278"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "8fd85405-c28b-42ce-87a8-646cbe38ced4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "723c410e-5789-4b21-abb9-d6ec05547ba9"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "blue-sky-e65b.221-553.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b1ecd06b-a931-47a2-8f48-d1d133d2b4f3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "3tmj2egtm-fno.49bnithzk8vphybv36d1z1xkzfvogt2m6.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "3tmj2egtm-fno.49bnithzk8vphybv36d1z1xkzfvogt2m6.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4c37df21-0a34-41bf-8bc7-78efd823c03b"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "shiny-salad-e491.479.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4e81922a-1c2e-41ee-bb4c-9095a0a363fe"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "gentle-cell-501a.273-d6b.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b3a11068-1a7e-4643-85de-7c82cce46943"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "rAHMmpeUJ6uOoGgk31dTF4-1RTtLZFnOEs_li2AYQWc"
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "401d950d-4f5c-45c7-bf44-8b69acf35f6f"
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiV3NqWVRNQlpFSVVwWmsiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119"
      headers:
        Host: "7x70yyvt7eqotx-iq9n3rjt1xn1jwkh9.asdfsafdsaf.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "fb5058f5-a9ed-424e-9ed7-33d455438286"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=Telegram🇨🇳 @WangCai2"
      headers:
        Host: "old-violet-a5ce.29-440.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime19.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "573bd634-8fad-46bd-9d76-7828df6dd05f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e8d06b09-acd9-448c-9874-3c36151d36ee"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "icy-wildflower-2590.lihuifeng595.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "9f534ac4-3c58-4a16-8b74-13dff09a0cf1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d39333476.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/pics/forum"
      headers:
        Host: "d39333476.pages.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "2b8738de-1af5-4267-b101-c05707769ed4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fans.liverpool.qzz.io"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiY0Y0cENQUmxsNyIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0="
      headers:
        Host: "fans.liverpool.qzz.io"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "ef5c5d5c-08c6-4549-b05e-d1ff29ecc8ba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "7-m16.CHiaN-MAi-8.KDNs.FR"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/JRr6VGcSLFc034DC6sDbwyWJLbB"
      headers:
        Host: "7-m16.CHiaN-MAi-8.KDNS.Fr"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "75323b6f-184f-4d00-839d-323b8fc70221"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "dry-sunset-f3c4.282.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b3a11068-1a7e-4643-85de-7c82cce46943"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "wGMBs7bvzyzA0-OUiwSkOOTDEMdxEOsSdRzxiP8GGQY"
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
